version: "3.3"
services:
  dashboard:
    build: "./dashboard"
    ports:
      - 80:8080
    volumes:
      - ./:/app
    command: ["R", "-e", "rmarkdown::run('./dashboard.Rmd', shiny_args = list(port = 8080, host = '0.0.0.0'))"]